language: php

dist: xenial

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

php:
    - 7.4

matrix:
    fast_finish: true
    include:
        -   env: PREFER_LOWEST="--prefer-lowest"
            script: composer tests
        -   before_install: pip install --user codecov
            script:
                - composer phpcs
                - composer phpmd
                - composer tests-cov
            after_success: bash <(curl -s https://codecov.io/bash)

install:
    - composer global require hirak/prestissimo
    - COMPOSER_MEMORY_LIMIT=-1 composer update $PREFER_LOWEST
