services:
    JG\SonataBatchEntityImportBundle\Admin\AdminImportExtension:
        arguments: ['%sonata_batch_entity_import.templates%']
        tags:
            - { name: sonata.admin.extension, global: true }

    JG\SonataBatchEntityImportBundle\Controller\ImportCrudController:
        public: true
        tags:
            - { name: batch_entity_import.controller }

    JG\SonataBatchEntityImportBundle\Twig\TemplateExtension:
        public: true
        arguments: ['%sonata_batch_entity_import.templates%']
        tags: [twig.extension]
